// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhkbipphvzvsaeulpbhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoa2JpcHBodnp2c2FldWxwYmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NDg5NjIsImV4cCI6MjA4ODAyNDk2Mn0.FYKLy2U0JDoBVQlOvQEJq10BLtDblJ9RSZXH0UezsTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});